name: infra-be-centralized-system

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  AWS_REGION: ap-southeast-2
  ACCOUNT_ID: 445567096757


jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        archive_name: [ [build_lib,"dev-libs"], [runtime_lib, ""]]
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Download python from action
        uses: ./.github/actions/download-python
      - name: Zipping package libraries
        uses: ./.github/actions/package-lib
        with:
          dev_lib_dir: ${{ matrix.archive_name[1] }}
          archive_name: ${{ matrix.archive_name[0] }}
      - name: List files for debugging
        run: ls -alh

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      - name: Install Node to setup cdk
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Download build_lib artifact
        uses: actions/download-artifact@v3
        with:
          name: build_lib
      - name: Download runtime_lib artifact
        uses: actions/download-artifact@v3
        with:
          name: runtime_lib
#      - name: Login to Amazon ECR
#        run: |
#          docker login -u AWS -p $(aws ecr get-login-password --region ${{ env.AWS_REGION }}) ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
#      - name: Deploy to ECR
#        run: |
#          docker build -t infra-be-centralized-system --build-arg ACCOUNT_ID="${{ env.ACCOUNT_ID }}" -f ./Dockerfile .
#          docker tag infra-be-centralized-system:latest ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/infra-be-centralized-system:${{ github.sha }}
#          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/infra-be-centralized-system:${{ github.sha }}
#          docker tag infra-be-centralized-system:latest ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/infra-be-centralized-system:latest
#          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/infra-be-centralized-system:latest
      - name: Deploy resources to AWS by CDK
        run: |
          sudo npm install -g aws-cdk@2.165.0
          PYTHONPATH=build_lib.zip cdk deploy --all -c src={PWD} --require-approval never
        shell: bash

